name: Setup R environment cache

on:
  schedule:
    # Run once a week at 00:00 on Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set R lib path
        run: echo "R_LIBS_USER=$HOME/R/library" >> $GITHUB_ENV

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/R/library
          key: ${{ runner.os }}-r-packages-v1
          restore-keys: ${{ runner.os }}-r-packages-

      - name: Install system dependencies
        run: |
          brew install gdal udunits

      - name: Install R packages
        run: Rscript -e 'install.packages(c("stringr","janitor","readr","dplyr","tidyr","sf","leaflet","htmlwidgets","leaflet.providers","leaflet.extras","htmltools"))'
                  
