# This is a basic workflow to help you get started with Actions

name: Downloader

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download a file
        uses: carlosperate/download-file-action@v1
        with:
          file-url: 'https://opendata.arcgis.com/datasets/2191f997056547bd9dc530ab9866ab61_0.geojson'
          file-name: 'active_perimeters.geojson'
          location: './datafiles'

      # Runs a set of commands using the runners shell
      - name: print file path
        run: echo "The file was downloaded to ${{ steps.download-file.outputs.file-path }}"       
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New fire files!' || echo "No changes"
          git push origin || echo "No changes to commit"